targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      retrofit_generator:
        enabled: true
      mockito:
        enabled: true
