// Mocks generated by Mockito 5.4.6 from annotations
// in cat_app/test/unit/favorites_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cat_app/features/favorites/data/datasources/favorites_api_service.dart'
    as _i3;
import 'package:cat_app/features/favorites/data/models/favorite_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCreateFavoriteResponse_0 extends _i1.SmartFake
    implements _i2.CreateFavoriteResponse {
  _FakeCreateFavoriteResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FavoritesApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesApiService extends _i1.Mock
    implements _i3.FavoritesApiService {
  MockFavoritesApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CreateFavoriteResponse> createFavorite(
    _i2.CreateFavoriteRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createFavorite, [request]),
            returnValue: _i4.Future<_i2.CreateFavoriteResponse>.value(
              _FakeCreateFavoriteResponse_0(
                this,
                Invocation.method(#createFavorite, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.CreateFavoriteResponse>);

  @override
  _i4.Future<List<_i2.FavoriteModel>> getFavorites({
    int? attachImage,
    String? imageId,
    String? subId,
    int? page,
    int? limit,
    String? order,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, [], {
              #attachImage: attachImage,
              #imageId: imageId,
              #subId: subId,
              #page: page,
              #limit: limit,
              #order: order,
            }),
            returnValue: _i4.Future<List<_i2.FavoriteModel>>.value(
              <_i2.FavoriteModel>[],
            ),
          )
          as _i4.Future<List<_i2.FavoriteModel>>);

  @override
  _i4.Future<void> deleteFavorite(int? favouriteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFavorite, [favouriteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
