// Mocks generated by Mockito 5.4.6 from annotations
// in cat_app/test/unit/favorites_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cat_app/core/errors/api_error_model.dart' as _i5;
import 'package:cat_app/features/favorites/data/models/favorite_model.dart'
    as _i6;
import 'package:cat_app/features/favorites/data/repositories/favorites_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i3.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ApiErrorModel, _i6.CreateFavoriteResponse>>
  createFavorite({required String? imageId, String? subId}) =>
      (super.noSuchMethod(
            Invocation.method(#createFavorite, [], {
              #imageId: imageId,
              #subId: subId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.ApiErrorModel, _i6.CreateFavoriteResponse>
                >.value(
                  _FakeEither_0<_i5.ApiErrorModel, _i6.CreateFavoriteResponse>(
                    this,
                    Invocation.method(#createFavorite, [], {
                      #imageId: imageId,
                      #subId: subId,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.ApiErrorModel, _i6.CreateFavoriteResponse>
          >);

  @override
  _i4.Future<_i2.Either<_i5.ApiErrorModel, List<_i6.FavoriteModel>>>
  getFavorites({
    String? subId,
    int? page,
    int? limit,
    String? order = 'DESC',
    bool? attachImage = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, [], {
              #subId: subId,
              #page: page,
              #limit: limit,
              #order: order,
              #attachImage: attachImage,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.ApiErrorModel, List<_i6.FavoriteModel>>
                >.value(
                  _FakeEither_0<_i5.ApiErrorModel, List<_i6.FavoriteModel>>(
                    this,
                    Invocation.method(#getFavorites, [], {
                      #subId: subId,
                      #page: page,
                      #limit: limit,
                      #order: order,
                      #attachImage: attachImage,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.ApiErrorModel, List<_i6.FavoriteModel>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.ApiErrorModel, void>> deleteFavorite(
    int? favouriteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFavorite, [favouriteId]),
            returnValue: _i4.Future<_i2.Either<_i5.ApiErrorModel, void>>.value(
              _FakeEither_0<_i5.ApiErrorModel, void>(
                this,
                Invocation.method(#deleteFavorite, [favouriteId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.ApiErrorModel, void>>);
}
